"""初始化数据库表

Revision ID: 3188176a52ad
Revises: 
Create Date: 2025-12-25 16:12:07.426904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3188176a52ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='对话ID（软外键 → conversations.id）'),
    sa.Column('api_type', sa.String(length=50), nullable=False, comment='API类型'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='Prompt内容'),
    sa.Column('response', sa.Text(), nullable=True, comment='AI响应'),
    sa.Column('tokens', sa.Integer(), nullable=True, comment='Token消耗'),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='成本（元）'),
    sa.Column('response_time', sa.Integer(), nullable=True, comment='响应时间（毫秒）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键（雪花算法）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('merchant_id', sa.BigInteger(), nullable=False, comment='商家ID（软外键 → merchants.id）'),
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='会话ID'),
    sa.Column('client_ip', sa.String(length=50), nullable=True, comment='客户IP'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='浏览器信息'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='来源（qrcode/link）'),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned'), nullable=False, comment='状态'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键（雪花算法）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('leads',
    sa.Column('merchant_id', sa.BigInteger(), nullable=False, comment='商家ID（软外键 → merchants.id）'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='对话ID（软外键 → conversations.id）'),
    sa.Column('phone', sa.String(length=255), nullable=False, comment='手机号（加密）'),
    sa.Column('wechat', sa.String(length=255), nullable=True, comment='微信号（加密）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='客户备注'),
    sa.Column('budget', sa.String(length=50), nullable=True, comment='预算'),
    sa.Column('device_type', sa.Enum('desktop', 'laptop', 'aio'), nullable=True, comment='设备类型'),
    sa.Column('usage', sa.String(length=50), nullable=True, comment='用途'),
    sa.Column('requirements', sa.Text(), nullable=True, comment='具体需求'),
    sa.Column('selected_sku_id', sa.BigInteger(), nullable=True, comment='选中方案ID（软外键 → skus.id）'),
    sa.Column('status', sa.Enum('pending', 'contacted', 'closed', 'abandoned'), nullable=False, comment='状态'),
    sa.Column('notes', sa.Text(), nullable=True, comment='跟进记录数组（JSON）'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键（雪花算法）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('merchants',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('shop_name', sa.String(length=100), nullable=False, comment='店铺名称'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='店铺地址'),
    sa.Column('business_hours', sa.String(length=50), nullable=True, comment='营业时间'),
    sa.Column('qrcode_url', sa.String(length=255), nullable=True, comment='二维码URL'),
    sa.Column('share_link', sa.String(length=255), nullable=False, comment='分享链接'),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=False, comment='状态'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键（雪花算法）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_link'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='对话ID（软外键 → conversations.id）'),
    sa.Column('role', sa.Enum('user', 'assistant'), nullable=False, comment='角色'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('extracted_info', sa.Text(), nullable=True, comment='AI提取的信息（JSON）'),
    sa.Column('confidence', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='置信度'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键（雪花算法）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_stats',
    sa.Column('merchant_id', sa.BigInteger(), nullable=False, comment='商家ID（软外键 → merchants.id）'),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('scan_count', sa.Integer(), nullable=False, comment='扫码数'),
    sa.Column('consult_count', sa.Integer(), nullable=False, comment='咨询数'),
    sa.Column('lead_count', sa.Integer(), nullable=False, comment='线索数'),
    sa.Column('device_type_stats', sa.Text(), nullable=True, comment='设备类型统计（JSON）'),
    sa.Column('budget_stats', sa.Text(), nullable=True, comment='预算分布统计（JSON）'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键（雪花算法）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skus',
    sa.Column('merchant_id', sa.BigInteger(), nullable=False, comment='商家ID（软外键 → merchants.id）'),
    sa.Column('device_type', sa.Enum('desktop', 'laptop', 'aio'), nullable=False, comment='设备类型'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='配置名称'),
    sa.Column('brand', sa.String(length=50), nullable=False, comment='品牌'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('cpu', sa.String(length=100), nullable=False, comment='处理器'),
    sa.Column('gpu', sa.String(length=100), nullable=True, comment='显卡'),
    sa.Column('ram', sa.String(length=50), nullable=False, comment='内存'),
    sa.Column('storage', sa.String(length=50), nullable=False, comment='存储'),
    sa.Column('motherboard', sa.String(length=100), nullable=True, comment='主板'),
    sa.Column('power_supply', sa.String(length=100), nullable=True, comment='电源'),
    sa.Column('case', sa.String(length=100), nullable=True, comment='机箱'),
    sa.Column('screen', sa.String(length=100), nullable=True, comment='屏幕'),
    sa.Column('weight', sa.String(length=20), nullable=True, comment='重量'),
    sa.Column('battery', sa.String(length=50), nullable=True, comment='续航'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='价格'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='库存'),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=False, comment='状态'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签数组（JSON）'),
    sa.Column('images', sa.Text(), nullable=True, comment='图片URL数组（JSON）'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='被查看次数'),
    sa.Column('select_count', sa.Integer(), nullable=False, comment='被选择次数'),
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键（雪花算法）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skus')
    op.drop_table('share_stats')
    op.drop_table('messages')
    op.drop_table('merchants')
    op.drop_table('leads')
    op.drop_table('conversations')
    op.drop_table('ai_logs')
    # ### end Alembic commands ###
