"""检测模型变更

Revision ID: 433fb9ddb36f
Revises: 3188176a52ad
Create Date: 2026-01-22 16:34:44.215108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '433fb9ddb36f'
down_revision: Union[str, None] = '3188176a52ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_logs', 'api_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='API类型（extraction/recommendation/modify）',
               existing_comment='API类型',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_logs', 'api_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='API类型',
               existing_comment='API类型（extraction/recommendation/modify）',
               existing_nullable=False)
    # ### end Alembic commands ###
